import assert from'node:assert/strict';import{mkdirSync,readFileSync,writeFileSync}from'node:fs';import AxeBuilder from'@axe-core/playwright';import{openBrowser}from'./browser-config.mjs';
const base=process.argv[2]??'http://127.0.0.1:5175/helio/',out=process.argv[3]??'qa-private/live',root=new URL(base).origin;mkdirSync(out,{recursive:true});const report={checkedAt:new Date().toISOString(),url:base,scope:'Directed real-browser interactions and screenshots; emulated viewport/touch, not physical devices or installed Safari; no screen-reader certification.',matrix:[],actions:[],engines:[],passed:false};
function persist(){writeFileSync(out+'/report.json',JSON.stringify(report,null,2));}
async function setRange(p,value){await p.locator('#time').evaluate((el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,String(v));el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);}
const browser=await openBrowser();
try{
const configs=[];for(const width of[360,390,768,1440])for(const lang of['ru','en'])for(const period of['day','night'])configs.push({width,lang,period});
configs.push({width:390,lang:'en',period:'day',view:'2d',reduced:true},{width:1440,lang:'ru',period:'night',reduced:true},{width:390,lang:'ru',period:'day',noWebGL:true},{width:390,lang:'ru',period:'day',text200:true});
for(const c of configs){const entry={...c,errors:[],external:[],badResponses:[],passed:false};report.matrix.push(entry);const ctx=await browser.newContext({viewport:{width:c.width,height:900},hasTouch:c.width<768,reducedMotion:c.reduced?'reduce':'no-preference',acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>entry.errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).origin!==root&&!r.url().startsWith('data:'))entry.external.push(r.url());});p.on('response',r=>{if(r.status()>=400)entry.badResponses.push({url:r.url(),status:r.status()});});
try{if(c.noWebGL)await p.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(/webgl/i.test(type))return null;return original.call(this,type,...args);};});await p.goto(base+'?city=astana&date=2026-10-02&lang='+c.lang+'&time='+(c.period==='day'?'12:00':'00:00')+(c.view?'&view='+c.view:''),{waitUntil:'networkidle',timeout:30000});await p.locator('time').waitFor();await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(500);
assert.equal(await p.locator('html').getAttribute('lang'),c.lang);assert.equal(await p.locator('time').innerText(),c.period==='day'?'12:00':'00:00');if(c.noWebGL||c.view)assert.equal(await p.locator('.fallback').count(),1);else assert.equal(await p.locator('canvas').count(),1);
if(c.text200){await p.evaluate(()=>{const nodes=[...document.querySelectorAll('*')].map(el=>[el,getComputedStyle(el).fontSize]);for(const[el,size]of nodes)el.style.fontSize=parseFloat(size)*2+'px';});const b=await p.locator('.language').boundingBox();assert(b.x>=0&&b.x+b.width<=c.width+1);}
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
entry.axe=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));assert.deepEqual(entry.axe,[]);assert.deepEqual(entry.errors,[]);assert.deepEqual(entry.external,[]);assert.deepEqual(entry.badResponses,[]);await p.screenshot({path:out+'/'+c.width+'-'+c.lang+'-'+c.period+(c.view?'-2d':'')+(c.noWebGL?'-no-webgl':'')+(c.text200?'-text200':'')+(c.reduced?'-reduced':'')+'.png'});entry.passed=true;console.log('matrix '+JSON.stringify(c)+' PASS');}catch(e){entry.failure=e.message;console.log('matrix FAIL '+e.message.slice(0,160));}finally{persist();await ctx.close();}}
for(const width of[390,1440]){const entry={width,checks:[],errors:[],passed:false};report.actions.push(entry);const ctx=await browser.newContext({viewport:{width,height:900},hasTouch:width<768,reducedMotion:'reduce',acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>entry.errors.push(e.message));
try{await p.goto(base+'?lang=en&date=2026-10-02',{waitUntil:'networkidle'});await p.locator('time').waitFor();const check=(name)=>entry.checks.push(name);
await p.locator('.skip').focus();await p.keyboard.press('Enter');assert.equal(new URL(p.url()).hash,'#planner');check('keyboard skip');
await p.locator('#time').focus();const before=await p.locator('time').innerText();await p.keyboard.press('ArrowRight');assert.notEqual(await p.locator('time').innerText(),before);check('keyboard scrubber');
for(const button of await p.locator('.event-row button:enabled').all()){const stamp=await button.locator('strong').innerText();await button.click();assert.equal(await p.locator('time').innerText(),stamp);}check('all seven event jumps');
for(const n of['north','east','south','west']){const b=p.getByRole('button',{name:'Look '+n,exact:true});await b.click();assert.equal(await b.getAttribute('aria-pressed'),'true');}await p.getByRole('button',{name:'Follow sun',exact:true}).click();check('four headings and follow');
await p.getByRole('button',{name:'Switch to 2D',exact:true}).click();assert.equal(await p.locator('.fallback-directions span').count(),5);await p.getByRole('button',{name:'Switch to 3D',exact:true}).click();await p.locator('canvas').waitFor();check('2D and 3D');
await p.getByRole('button',{name:'Switch to Russian',exact:true}).click();assert.equal(await p.locator('html').getAttribute('lang'),'ru');await p.getByRole('button',{name:'Переключить на английский',exact:true}).click();check('languages');
const dateInput=p.locator('input[type=date]');await p.getByRole('button',{name:'Next day',exact:true}).click();assert.equal(await dateInput.inputValue(),'2026-10-03');await p.getByRole('button',{name:'Previous day',exact:true}).click();assert.equal(await dateInput.inputValue(),'2026-10-02');await p.getByRole('button',{name:'Now',exact:true}).click();assert(Math.abs(Date.now()-Date.parse(await p.locator('time').getAttribute('datetime')))<5000);check('day navigation and now');
for(const city of['astana','almaty','london','new-york','tokyo','sydney','tromso','kathmandu','kiritimati']){await p.locator('.control-row select').selectOption(city);await p.waitForTimeout(30);assert.equal(await p.locator('.control-row select').inputValue(),city);}check('all city options');
await p.locator('.control-row select').selectOption('new-york');await dateInput.fill('2026-11-01');await p.waitForTimeout(100);await setRange(p,'90');assert.equal(await p.locator('time').innerText(),'01:30');assert((await p.locator('.clock-zone').innerText()).includes('-04:00'));await setRange(p,'150');assert.equal(await p.locator('time').innerText(),'01:30');assert((await p.locator('.clock-zone').innerText()).includes('-05:00'));check('two DST 01:30 instants');
await p.getByRole('button',{name:'Save on this device',exact:true}).click();await setRange(p,'300');await p.getByRole('button',{name:'Open saved',exact:true}).click();assert.equal(await p.locator('time').innerText(),'01:30');await p.getByRole('button',{name:'Delete saved',exact:true}).click();assert.equal(await p.evaluate(()=>localStorage.getItem('helio.saved-plan.v1')),null);check('explicit save restore delete');
for(const [label,ext]of[['Download plan','.json'],['Add to calendar','.ics']]){const[d]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:new RegExp('^'+label)}).click()]);assert(d.suggestedFilename().endsWith(ext));const file=out+'/'+width+ext;await d.saveAs(file);const data=readFileSync(file,'utf8');if(ext==='.json'){const j=JSON.parse(data);assert.equal(j.timeZone,'America/New_York');assert.equal(j.selectedOffset,'-05:00');}else assert(data.includes('BEGIN:VCALENDAR\r\n')&&data.includes('DTSTART:'));}check('actual JSON and ICS downloads');
await p.locator('.manual summary').click();const fields=p.locator('.manual input');await fields.nth(0).fill('91');await p.getByRole('button',{name:'Use location',exact:true}).click();assert((await p.getByRole('status').innerText()).includes('latitude'));await fields.nth(0).fill('27.7172');await fields.nth(1).fill('85.324');await fields.nth(2).fill('Asia/Kathmandu');await p.getByRole('button',{name:'Use location',exact:true}).click();assert.equal(await p.locator('.control-row select').inputValue(),'custom');assert((await p.locator('.clock-zone').innerText()).includes('+05:45'));await p.locator('.manual summary').click();check('manual coordinates and recovery');
const zone=p.locator('.zone-field input');await zone.fill('Bad/Zone');await p.getByRole('button',{name:'Apply',exact:true}).click();assert((await p.getByRole('status').innerText()).includes('IANA'));await zone.fill('UTC');await p.getByRole('button',{name:'Apply',exact:true}).click();assert((await p.locator('.clock-zone').innerText()).includes('+00:00'));check('IANA edit and error');
await p.locator('.control-row select').selectOption('tromso');await dateInput.fill('2026-12-21');await p.waitForTimeout(100);assert((await p.locator('.day-summary').innerText()).includes('does not rise'));assert.equal(await p.locator('.event-row button').filter({has:p.locator('span', {hasText:/^Sunrise$/})}).isDisabled(),true);check('polar night with twilight');
const[popup]=await Promise.all([p.waitForEvent('popup'),p.getByRole('link',{name:'Code & method'}).click()]);await popup.waitForURL(/^https:\/\/github\.com\/MOYISEY\/helio/i,{timeout:30000});await popup.waitForLoadState('domcontentloaded');assert(/^https:\/\/github\.com\/MOYISEY\/helio/i.test(popup.url()));assert.equal(await popup.evaluate(()=>opener===null),true);await popup.close();check('source link actual popup');
await p.getByRole('link',{name:'Helio home',exact:true}).click();await p.locator('time').waitFor();assert.equal(new URL(p.url()).search,'');check('brand home');assert.deepEqual(entry.errors,[]);entry.passed=true;console.log('actions '+width+' '+entry.checks.length+' groups PASS');}catch(e){entry.failure=e.message;console.log('actions '+width+' FAIL '+e.message.slice(0,180));}finally{persist();await ctx.close();}}
}finally{await browser.close();}
for(const engine of['firefox','webkit']){const entry={engine,errors:[],passed:false};report.engines.push(entry);let b;try{b=await openBrowser({},engine);const context=await b.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});const p=await context.newPage();p.on('pageerror',e=>entry.errors.push(e.message));await p.goto(base+'?lang=en&city=new-york&date=2026-03-08&time=12:00',{waitUntil:'networkidle',timeout:30000});await p.locator('time').waitFor();assert.equal(await p.locator('time').innerText(),'12:00');assert.equal(await p.locator('#time').getAttribute('max'),'1379');await setRange(p,'60');assert.equal(await p.locator('time').innerText(),'01:00');await p.screenshot({path:out+'/'+engine+'-390.png'});assert.deepEqual(entry.errors,[]);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);entry.passed=true;console.log(engine+' engine PASS');}catch(e){entry.failure=e.message;console.log(engine+' FAIL '+e.message.slice(0,180));}finally{await b?.close();persist();}}
report.passed=[...report.matrix,...report.actions,...report.engines].every(x=>x.passed);persist();if(!report.passed)process.exitCode=1;

