import {Component,lazy,Suspense,useCallback,useEffect,useMemo,useState,type ReactNode} from 'react';
import{calculateDay,formatTime,places,positionAt,seekMinute,shiftDate,today,utcOffset,phaseAt,type Place,type EventId}from'./solar.ts';
import{initialSettings,parseSaved,STORAGE_KEY,type SavedPlan}from'./state.ts';
import{download,exportPlan,exportCalendar}from'./export.ts';
import Fallback from './Fallback';
const Scene=lazy(()=>import('./Scene'));
const MapPanel=lazy(()=>import('./MapPanel'));
class SceneBoundary extends Component<{children:ReactNode;fail:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}componentDidCatch(){this.props.fail();}render(){return this.state.failed?null:this.props.children;}}
function useReduced(){const[q,set]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),f=()=>set(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f);},[]);return q;}
const ruEvents:Record<EventId,string>={dawn:'Утренние сумерки',sunrise:'Рассвет',goldenEnd:'Мягкий свет до',noon:'Солнечный полдень',goldenStart:'Мягкий свет с',sunset:'Закат',dusk:'Вечерние сумерки до'};
const enEvents:Record<EventId,string>={dawn:'Civil dawn',sunrise:'Sunrise',goldenEnd:'Golden light ends',noon:'Solar noon',goldenStart:'Golden light starts',sunset:'Sunset',dusk:'Civil dusk'};
export default function App(){
 const initial=useMemo(()=>initialSettings(),[]),[lang,setLang]=useState(initial.lang),[selection,setSelection]=useState(()=>({plan:calculateDay(initial.date,initial.place),instant:initial.instant}));
 const{plan,instant}=selection,{place,date}=plan,en=lang==='en',reduced=useReduced();
 const[fallback,setFallback]=useState(initial.view),[webglFailed,setWebglFailed]=useState(false),[heading,setHeading]=useState<number|null>(null);
 const[view,setView]=useState<'map'|'horizon'>(initial.view?'horizon':'map'),[cityQuery,setCityQuery]=useState('');
 const[message,setMessage]=useState(initial.error?'url':''),[zoneDraft,setZoneDraft]=useState(place.zone),[dateDraft,setDateDraft]=useState(date),[lat,setLat]=useState('51.1694'),[lon,setLon]=useState('71.4491'),[manualZone,setManualZone]=useState('Asia/Almaty'),[saved,setSaved]=useState(false);
 const pos=useMemo(()=>positionAt(instant,place),[instant,place]),phase=phaseAt(instant,plan);
 useEffect(()=>{document.documentElement.lang=lang;document.title=en?'Helio — Daylight Atlas':'Helio — атлас дневного света';},[lang,en]);
 useEffect(()=>{setDateDraft(date);setZoneDraft(place.zone);},[date,place]);
 useEffect(()=>{try{setSaved(localStorage.getItem(STORAGE_KEY)!==null);}catch{}},[]);
 const fail=useCallback(()=>{setFallback(true);setWebglFailed(true);},[]);
 const fmt=(epoch:number)=>formatTime(epoch,place.zone,lang),name=en?place.en:place.ru;
 function change(nextDate:string,nextPlace=place,nextInstant?:number){try{const next=calculateDay(nextDate,nextPlace),oldRatio=(instant-plan.start)/(plan.end-plan.start),at=nextInstant??next.start+oldRatio*(next.end-next.start);setSelection({plan:next,instant:Math.max(next.start,Math.min(next.end-1,at))});setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'date');}}
 function move(days:number){try{change(shiftDate(date,days));}catch{setMessage('date');}}
 function now(){const at=Date.now();change(today(place.zone,at),place,at);}
 function applyManual(){if(!lat.trim()||!lon.trim()){setMessage('coordinates');return;}const p:Place={id:'custom',ru:'Своя точка',en:'Custom location',lat:Number(lat),lon:Number(lon),zone:manualZone.trim()};change(date,p);}
 function save(){try{const value:SavedPlan={version:1,place,date,instant};localStorage.setItem(STORAGE_KEY,JSON.stringify(value));setSaved(true);setMessage('saved');}catch{setMessage('storage');}}
 function restore(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)throw Error();const s=parseSaved(raw);change(s.date,s.place,s.instant);setMessage('restored');}catch{setMessage('saved-invalid');}}
 function remove(){try{localStorage.removeItem(STORAGE_KEY);setSaved(false);setMessage('removed');}catch{setMessage('storage');}}
 function output(kind:'json'|'ics'){try{download('helio-'+date+'.'+kind,kind==='json'?exportPlan(plan,instant,lang):exportCalendar(plan,instant,lang),kind==='json'?'application/json':'text/calendar;charset=utf-8');setMessage('exported');}catch{setMessage('export-failed');}}
 const messages:Record<string,[string,string]>={
 url:['Часть параметров ссылки некорректна. Использованы доступные настройки.','Some link settings are invalid. Available defaults were used.'],
 coordinates:['Введите широту от −90 до 90 и долготу от −180 до 180.','Enter latitude from −90 to 90 and longitude from −180 to 180.'],
 zone:['Проверьте IANA-зону, например Europe/London или Asia/Almaty.','Check the IANA zone, such as Europe/London or Asia/Almaty.'],
 date:['Выберите существующую дату между 1900 и 2100 годами.','Choose a valid date between 1900 and 2100.'],
 'skipped-date':['Эта календарная дата отсутствует в выбранной зоне. Выберите соседнюю.','This calendar date does not exist in this zone. Choose an adjacent day.'],
 saved:['План сохранён только на этом устройстве.','Plan saved on this device.'],
 restored:['Сохранённый план открыт.','Saved plan restored.'],removed:['Сохранённый план удалён.','Saved plan deleted.'],
 storage:['Браузер не разрешил сохранение. План можно скачать.','Browser storage is unavailable. You can download the plan.'],
 'saved-invalid':['Сохранённые данные не удалось открыть. Их можно удалить.','Saved data could not be restored. You can delete it.'],
 exported:['Файл плана готов.','Plan file is ready.'],'export-failed':['Не удалось подготовить файл. Попробуйте снова.','File could not be prepared. Try again.']
 };
 const phaseName={night:en?'Night':'Ночь',twilight:en?'Civil twilight':'Гражданские сумерки',golden:en?'Golden light':'Мягкий свет',day:en?'Daylight':'Дневной свет'}[phase];
 const eventNames=en?enEvents:ruEvents;
 const daylight=Math.round(plan.daylightMinutes),hours=Math.floor(daylight/60),minutes=daylight%60;
 const important:EventId[]=['dawn','sunrise','goldenEnd','noon','goldenStart','sunset','dusk'];
 return <main className={(phase==='night'?'night':'day')+' atlas-v2 '+view+'-view'}>
 <a className="skip" href="#planner">{en?'Go to planner':'К планировщику'}</a>
 <header><a className="brand" href="/helio/" aria-label={en?'Helio home':'Helio — главная'}>helio<span aria-hidden="true">✦</span></a><span className="edition">DAYLIGHT ATLAS <i>01</i></span><button className="language" onClick={()=>setLang(en?'ru':'en')} aria-label={en?'Switch to Russian':'Переключить на английский'}>{en?'RU':'EN'}</button></header>
 <section className="hero" aria-labelledby="title">
 {view==='horizon'&&<div className="world">{fallback?<Fallback position={pos}/>:<SceneBoundary key="scene" fail={fail}><Suspense fallback={<Fallback position={pos}/>}><Scene position={pos} heading={heading} reduced={reduced} onFallback={fail}/></Suspense></SceneBoundary>}</div>}
 <div className="hero-copy"><p className="eyebrow">{en?'A little closer to the sun':'Немного ближе к солнцу'}</p><h1 id="title">{en?<>Find your<br/><em>kind of light.</em></>:<>Застаньте<br/><em>свой свет.</em></>}</h1><p className="intro">{en?'A sunrise worth getting up for. A walk before the city turns blue. Find the moment — and make a plan.':'Рассвет, ради которого стоит встать. Прогулка, пока город не стал синим. Найдите момент — и запланируйте его.'}</p></div>
 <div className="solar-readout"><span className="phase">{phaseName}</span><strong><time dateTime={new Date(instant).toISOString()}>{fmt(instant)}</time></strong><p>{pos.altitude.toFixed(1)}° {en?'above the horizon':'над горизонтом'} <span>↗ {pos.azimuth.toFixed(0)}°</span></p><p className="clock-zone">{name} · UTC{utcOffset(instant,place.zone)}</p></div>
 <div className="atlas-modes" aria-label={en?'Atlas view':'Режим атласа'}><button aria-pressed={view==='map'} onClick={()=>setView('map')}>{en?'City & shadows':'Город и тени'}</button><button aria-pressed={view==='horizon'} onClick={()=>setView('horizon')}>{en?'Open horizon':'Открытый горизонт'}</button></div>
 {view==='map'&&<><div className="city-search"><label htmlFor="city-search">{en?'City search':'Поиск города'}<input id="city-search" type="search" value={cityQuery} onChange={e=>setCityQuery(e.target.value)} placeholder={en?'Astana, London, Tokyo…':'Астана, Лондон, Токио…'} autoComplete="off" maxLength={60}/></label><p>{en?'Nine cities in an offline list. Choose a street or courtyard on the map. Moving the point keeps the selected time zone — check it when changing regions.':'Девять городов в локальном списке. Улицу или двор выберите на карте. При перемещении точки часовая зона сохраняется — проверьте её при смене региона.'}</p>{cityQuery&&<div className="city-results" aria-label={en?'Matching cities':'Найденные города'}>{places.filter(p=>(p.ru+' '+p.en+' '+p.id).toLowerCase().includes(cityQuery.trim().toLowerCase())).map(p=><button key={p.id} onClick={()=>{change(date,p);setCityQuery('');}}>{en?p.en:p.ru}<span>{p.zone}</span></button>)}{!places.some(p=>(p.ru+' '+p.en+' '+p.id).toLowerCase().includes(cityQuery.trim().toLowerCase()))&&<p role="status">{en?'No city in this list. Move the map or use coordinates below.':'Такого города в списке нет. Переместите карту или укажите координаты ниже.'}</p>}</div>}</div><Suspense fallback={<p className="map-loading" role="status">{en?'Preparing the map…':'Готовим карту…'}</p>}><MapPanel place={place} position={pos} en={en} reduced={reduced} minute={Math.round((instant-plan.start)/60000)} minutes={plan.minutes} timeLabel={fmt(instant)+' UTC'+utcOffset(instant,place.zone)} onMinute={minute=>setSelection({plan,instant:seekMinute(plan,minute)})} onPoint={(lon,lat)=>change(date,{id:'custom',ru:'Точка на карте',en:'Map point',lat,lon,zone:place.zone})}/></Suspense></>}
 {view==='horizon'&&<>
 <div className="scene-caption"><span className="status-dot"/><span>{en?'Artistic world. Calculated apparent sun.':'Условный мир. Видимое положение солнца — по расчёту.'}</span><div className="view-controls" aria-label={en?'View direction':'Направление взгляда'}>{!fallback&&<><button onClick={()=>setHeading(null)} aria-pressed={heading===null}>{en?'Follow sun':'За солнцем'}</button>{[['N',0],['E',90],['S',180],['W',270]].map(([n,a])=><button key={n} onClick={()=>setHeading(Number(a))} aria-pressed={heading===a} aria-label={(en?'Look ':'Вид: ')+({N:en?'north':'север',E:en?'east':'восток',S:en?'south':'юг',W:en?'west':'запад'}[String(n)])}>{n}</button>)}</>}<button className="mode-toggle" onClick={()=>{if(fallback){setWebglFailed(false);setFallback(false);}else setFallback(true);}} aria-label={fallback?(en?'Switch to 3D':'Включить 3D'):(en?'Switch to 2D':'Включить 2D')}>{fallback?'3D':'2D'}</button></div></div>
 {webglFailed&&<p className="fallback-note">{en?'3D is unavailable here. The 2D view uses the same solar calculations.':'3D здесь недоступно. В 2D работают те же расчёты положения солнца.'}</p>}
 </>}
 <section className="planner" id="planner" aria-label={en?'Daylight planner':'Планировщик света'}>
 <div className="control-row"><label>{en?'Place':'Место'}<select value={place.id} onChange={e=>{const p=places.find(p=>p.id===e.target.value);if(p)change(date,p);}}>{places.map(c=><option value={c.id} key={c.id}>{en?c.en:c.ru}</option>)}{place.id==='custom'&&<option value="custom">{en?'Custom location':'Своя точка'}</option>}</select></label>
 <label>{en?'Calendar date':'Календарная дата'}<input type="date" min="1900-01-01" max="2100-12-31" value={dateDraft} onChange={e=>{setDateDraft(e.target.value);if(e.target.value)change(e.target.value);else setMessage('date');}}/></label>
 <form className="zone-field" onSubmit={e=>{e.preventDefault();change(date,{...place,zone:zoneDraft.trim()});}}><label>{en?'IANA time zone':'Часовая зона IANA'}<input value={zoneDraft} list="zones" onChange={e=>setZoneDraft(e.target.value)} maxLength={80} required/></label><button type="submit">{en?'Apply':'Применить'}</button><datalist id="zones">{[...new Set(places.map(p=>p.zone)),'UTC'].map(z=><option value={z} key={z}/>)}</datalist></form></div>
 <div className="day-tools"><div className="date-navigation"><button onClick={()=>move(-1)} aria-label={en?'Previous day':'Предыдущий день'} disabled={date==='1900-01-01'}>←</button><button onClick={now}>{en?'Now':'Сейчас'}</button><button onClick={()=>move(1)} aria-label={en?'Next day':'Следующий день'} disabled={date==='2100-12-31'}>→</button></div><p>{place.lat.toFixed(4)}°, {place.lon.toFixed(4)}° <span>· {plan.minutes/60} {en?'hour day':'ч в этих сутках'}</span></p></div>
 <div className="scrubber"><label htmlFor="time">{en?'Move through the local day':'Проведите день по шкале'} <span>{en?'Elapsed time; UTC offset distinguishes repeated hours.':'Реальное время; UTC-смещение различает повторный час.'}</span></label><div className="time-track" aria-hidden="true">{plan.intervals.map((x,i)=><span className={'band '+x.kind} key={i} style={{left:((x.start-plan.start)/(plan.end-plan.start)*100)+'%',width:((x.end-x.start)/(plan.end-plan.start)*100)+'%'}}/>)}</div><input id="time" type="range" min="0" max={Math.ceil(plan.minutes)-1} step="1" value={Math.min(Math.ceil(plan.minutes)-1,Math.round((instant-plan.start)/60000))} onChange={e=>setSelection({plan,instant:seekMinute(plan,Number(e.target.value))})} aria-valuetext={fmt(instant)+' UTC'+utcOffset(instant,place.zone)+', '+phaseName}/><div className="ticks">{[0,.25,.5,.75,1].map((x,i)=><span key={i}>{formatTime(x===1?plan.end-60000:plan.start+(plan.end-plan.start)*x,place.zone,lang)}</span>)}</div><div className="legend"><span className="golden-dot"/>{en?'Golden light':'Мягкий свет'}<span className="twilight-dot"/>{en?'Civil twilight':'Гражданские сумерки'}</div></div>
 <div className="day-summary"><p>{plan.state==='polarDay'?(en?'The sun stays above the horizon today.':'Сегодня солнце не заходит.'):plan.state==='polarNight'?(en?'The sun does not rise today. Twilight may still occur.':'Сегодня солнце не восходит. Сумерки при этом возможны.'):(en?'Daylight':'Световой день')+' · '+hours+(en?' h ':' ч ')+minutes+(en?' min':' мин')}</p><span>{en?'Open horizon · estimate':'Открытый горизонт · ориентир'}</span></div>
 <div className="event-row">{important.map(id=>{const event=plan.events.find(e=>e.id===id);return <button key={id} className={'event '+(id.startsWith('golden')?'golden-event':'')} disabled={!event} onClick={()=>event&&setSelection({plan,instant:event.at})} aria-label={event?eventNames[id]+', '+fmt(event.at):eventNames[id]+(en?' does not occur':' — события нет')}><span>{eventNames[id]}</span><strong>{event?fmt(event.at):'—'}</strong><small>{event?utcOffset(event.at,place.zone):(en?'No crossing today':'Нет пересечения')}</small></button>;})}</div>
 {message&&<p className="message" role="status">{messages[message]?.[en?1:0]??messages.date[en?1:0]}</p>}
 <div className="plan-actions"><button className="primary-action" onClick={()=>output('json')}>{en?'Download plan':'Скачать план'} <span>↗ JSON</span></button><button onClick={()=>output('ics')}>{en?'Add to calendar':'В календарь'} <span>ICS</span></button><button onClick={save}>{en?'Save on this device':'Сохранить на устройстве'}</button>{saved&&<><button onClick={restore}>{en?'Open saved':'Открыть сохранённый'}</button><button onClick={remove}>{en?'Delete saved':'Удалить сохранённый'}</button></>}</div>
 <details className="manual"><summary>{en?'Enter coordinates instead':'Указать координаты вручную'}</summary><p>{en?'Enter coordinates and an explicit time zone. In city mode, the map provider receives viewport requests for this location.':'Введите координаты и явную часовую зону. В режиме города провайдер карты получает запросы области просмотра для этой точки.'}</p><form onSubmit={e=>{e.preventDefault();applyManual();}}><label>{en?'Latitude':'Широта'}<input inputMode="decimal" value={lat} onChange={e=>setLat(e.target.value)} maxLength={20} required/></label><label>{en?'Longitude':'Долгота'}<input inputMode="decimal" value={lon} onChange={e=>setLon(e.target.value)} maxLength={20} required/></label><label>{en?'IANA time zone':'Часовая зона IANA'}<input value={manualZone} onChange={e=>setManualZone(e.target.value)} maxLength={80} required/></label><button type="submit">{en?'Use location':'Использовать точку'}</button></form></details>
 </section></section>
 <section className="method" aria-labelledby="method-title"><div><p className="eyebrow">THE LIGHT, EXPLAINED</p><h2 id="method-title">{en?<>The moment changes.<br/><em>The plan is yours.</em></>:<>Свет меняется.<br/><em>План остаётся вашим.</em></>}</h2></div><div className="method-copy"><p>{en?'Golden light here means the sun is between standard sunrise/sunset (−0.833° geometric altitude) and +6°. Civil twilight is the interval from −6° to sunrise, and from sunset to −6°. At high latitudes a window can last much longer than an hour.':'Мягким светом здесь называем промежуток от стандартного рассвета или заката (−0,833° геометрической высоты) до +6°. Гражданские сумерки — от −6° до рассвета и от заката до −6°. На севере такое окно может длиться намного дольше часа.'}</p><p>{en?'Solar event times are rounded to the nearest minute for an open horizon and standard refraction. The neighborhood tests shadows separately, using only loaded building contours and estimated heights on flat ground. The open-horizon scene has an artistic scale. Clouds, trees, terrain and actual illumination remain outside both estimates.':'Время солнечных событий округлено до ближайшей минуты для открытого горизонта и стандартной рефракции. Тени квартала проверяются отдельно: только загруженные контуры зданий с оценочными высотами на плоской земле. Масштаб сцены открытого горизонта художественный. Облака, деревья, рельеф и фактическая освещённость в эти оценки не входят.'}</p><p>{en?'Nothing is saved automatically. Device saving and file exports happen only when you choose them.':'Автоматического сохранения нет. Запись на устройство и выгрузка файла происходят только по вашему нажатию.'}</p></div></section>
 <footer><p>{en?'Look up. Leave some room for wonder.':'Поднимите глаза. Оставьте место удивлению.'}</p><a href="https://github.com/MOYISEY/helio" target="_blank" rel="noopener noreferrer">{en?'Code & method':'Код и методика'} ↗</a></footer>
 </main>;
}
