import type{DayPlan}from'./solar.ts';import{utcOffset}from'./solar.ts';
export function exportPlan(plan:DayPlan,selected:number,lang:'ru'|'en'){
 return JSON.stringify({product:'Helio / Daylight Atlas',version:1,calendarDate:plan.date,timeZone:plan.place.zone,place:{name:lang==='ru'?plan.place.ru:plan.place.en,latitude:plan.place.lat,longitude:plan.place.lon},selectedInstant:new Date(selected).toISOString(),selectedOffset:utcOffset(selected,plan.place.zone),day:{start:new Date(plan.start).toISOString(),end:new Date(plan.end).toISOString(),elapsedMinutes:plan.minutes,state:plan.state,daylightMinutes:Math.round(plan.daylightMinutes)},events:plan.events.map(e=>({name:e.id,instant:new Date(e.at).toISOString(),offset:utcOffset(e.at,plan.place.zone)})),lightIntervals:plan.intervals.map(x=>({phase:x.kind,start:new Date(x.start).toISOString(),end:new Date(x.end).toISOString()})),method:{engine:'SunCalc 2.1.0',golden:'Geometric solar altitude from -0.833° (standard sunrise/set) to +6°',civilTwilight:'Geometric solar altitude from -6° to -0.833°',horizon:'Unobstructed horizon, observer height 0 m, standard refraction. No weather or terrain included.',scene:'Artistic scale; calculated apparent position.'}},null,2);
}
const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
const stamp=(epoch:number)=>new Date(epoch).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
export function exportCalendar(plan:DayPlan,selected:number,lang:'ru'|'en',now=Date.now()){
 const name=lang==='ru'?plan.place.ru:plan.place.en;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Helio//Daylight Atlas//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:'+stamp(selected)+'-'+Math.round(plan.place.lat*10000)+'-'+Math.round(plan.place.lon*10000)+'@helio.local','DTSTAMP:'+stamp(now),'DTSTART:'+stamp(selected),'DTEND:'+stamp(selected+30*60000),'SUMMARY:'+escape((lang==='ru'?'План света — ':'Light plan — ')+name),'DESCRIPTION:'+escape('Helio. '+plan.place.zone+'; '+plan.date+'. Open horizon estimate, no weather or terrain. Golden: sunrise to +6 degrees and +6 degrees to sunset.'),'END:VEVENT','END:VCALENDAR'];
 // Fold by UTF-8 octets, never split a code point (RFC 5545).
 return lines.map(line=>{let out='',size=0;for(const c of line){const bytes=new TextEncoder().encode(c).length;if(size+bytes>74){out+='\r\n ';size=1;}out+=c;size+=bytes;}return out;}).join('\r\n')+'\r\n';
}
export function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
