import {useEffect,useRef,useState} from 'react';
import {Map as LibreMap,Marker,AttributionControl,ScaleControl,setWorkerUrl,type GeoJSONSource} from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import {areaBounds,buildNeighborhood,type Neighborhood,type Feature} from './buildings.ts';
import {ShadowLayer,type Shade} from './ShadowLayer.ts';
import type {Place} from './solar.ts';
setWorkerUrl(workerUrl);
type Props={place:Place;position:{azimuth:number;altitude:number};en:boolean;reduced:boolean;onPoint:(lon:number,lat:number)=>void;minute:number;minutes:number;timeLabel:string;onMinute:(minute:number)=>void;onRetry:()=>void};
const shadeText:Record<Shade,[string,string]>={night:['Солнце ниже горизонта','Sun below the horizon'],inside:['Точка внутри здания. Выберите место снаружи.','Point inside a building. Choose a spot outside.'],shade:['Тень от учтённого здания','Shadow from a loaded building'],clear:['Учтённые здания не перекрывают солнце','Loaded buildings do not block the sun'],insufficient:['Данных недостаточно','Insufficient data']};
const wrapLongitude=(lon:number)=>((lon+180)%360+360)%360-180;
export default function MapPanel({place,position,en,reduced,onPoint,minute,minutes,timeLabel,onMinute,onRetry}:Props){
 const host=useRef<HTMLDivElement>(null),mapRef=useRef<LibreMap|null>(null),markerRef=useRef<Marker|null>(null),layerRef=useRef<ShadowLayer|null>(null),latest=useRef({place,position,en,reduced,onPoint}),generation=useRef(0),cancelWait=useRef<(()=>void)|null>(null),visible=useRef(true),sourceError=useRef(false);
 latest.current={place,position,en,reduced,onPoint};
 const[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[network,setNetwork]=useState(false),[building,setBuilding]=useState(false),[model,setModel]=useState<Neighborhood|null>(null),[shade,setShade]=useState<Shade>('insufficient'),[pitched,setPitched]=useState(false);
 function clear(){generation.current++;cancelWait.current?.();cancelWait.current=null;const map=mapRef.current;if(map?.getLayer('helio-neighborhood'))map.removeLayer('helio-neighborhood');layerRef.current=null;setModel(null);setShade('insufficient');setBuilding(false);}
 function border(){const map=mapRef.current;if(!map?.getSource('helio-boundary'))return;const p=latest.current.place,b=areaBounds(p.lon,p.lat);(map.getSource('helio-boundary') as GeoJSONSource).setData({type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[b[0][0],b[0][1]],[b[1][0],b[0][1]],[b[1][0],b[1][1]],[b[0][0],b[1][1]],[b[0][0],b[0][1]]]]}});}
 useEffect(()=>{let map:LibreMap|undefined,disposed=false;setFailed(false);try{
  map=new LibreMap({container:host.current!,style:'https://tiles.openfreemap.org/styles/liberty',center:[latest.current.place.lon,Math.max(-85,Math.min(85,latest.current.place.lat))],zoom:16,pitch:0,maxPitch:65,minZoom:2,maxZoom:19,renderWorldCopies:false,pixelRatio:Math.min(devicePixelRatio,1.5),maxTileCacheSize:80,canvasContextAttributes:{antialias:true},attributionControl:false});mapRef.current=map;map.addControl(new AttributionControl({compact:false}),'bottom-right');map.addControl(new ScaleControl({maxWidth:90}),'bottom-left');map.scrollZoom.disable();
  const pin=document.createElement('button');pin.type='button';pin.className='map-pin';pin.textContent='✦';pin.addEventListener('click',e=>e.stopPropagation());const marker=new Marker({element:pin,draggable:true,anchor:'center'}).setLngLat([latest.current.place.lon,latest.current.place.lat]).addTo(map);markerRef.current=marker;
  marker.on('dragend',()=>{const p=marker.getLngLat();latest.current.onPoint(wrapLongitude(p.lng),p.lat);});map.on('click',e=>latest.current.onPoint(wrapLongitude(e.lngLat.lng),e.lngLat.lat));
  map.on('error',()=>{if(!disposed){sourceError.current=true;setNetwork(true);setShade('insufficient');}});map.getCanvas().addEventListener('webglcontextlost',()=>{if(!disposed){setFailed(true);setShade('insufficient');}});
  const timer=window.setTimeout(()=>{if(!map?.isStyleLoaded())setNetwork(true);},18000);
  map.on('style.load',()=>{window.clearTimeout(timer);setReady(true);setNetwork(false);const style=map!.getStyle();for(const l of style.layers){if(l.type==='fill-extrusion')map!.setLayoutProperty(l.id,'visibility','none');if(l.type==='fill'&&l['source-layer']==='building'){map!.setLayerZoomRange(l.id,13,24);map!.setPaintProperty(l.id,'fill-color','#d4cebd');}}map!.addSource('helio-boundary',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map!.addLayer({id:'helio-boundary-line',type:'line',source:'helio-boundary',paint:{'line-color':'#304d88','line-width':2,'line-dasharray':[3,2]}});border();});
  const observer=new ResizeObserver(()=>map?.resize());observer.observe(host.current!);
  return()=>{disposed=true;window.clearTimeout(timer);observer.disconnect();cancelWait.current?.();generation.current++;marker.remove();map?.remove();mapRef.current=null;markerRef.current=null;layerRef.current=null;};
 }catch{map?.remove();setFailed(true);mapRef.current=null;}},[]);
 useEffect(()=>{let intersects=true,disposed=false;const sync=()=>{if(disposed)return;visible.current=intersects&&!document.hidden;const layer=layerRef.current;if(layer&&layer.active!==visible.current){layer.active=visible.current;if(layer.active)layer.setSun(latest.current.position.azimuth,latest.current.position.altitude);}};const observer=new IntersectionObserver(entries=>{intersects=entries[0]?.isIntersecting??false;sync();});if(host.current)observer.observe(host.current);document.addEventListener('visibilitychange',sync);sync();return()=>{disposed=true;observer.disconnect();document.removeEventListener('visibilitychange',sync);};},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;clear();markerRef.current?.setLngLat([place.lon,Math.max(-85,Math.min(85,place.lat))]);border();const p=map.project([place.lon,place.lat]);if(p.x<50||p.y<50||p.x>map.getCanvas().clientWidth-50||p.y>map.getCanvas().clientHeight-50)map.easeTo({center:[place.lon,Math.max(-85,Math.min(85,place.lat))],pitch:0,bearing:0,zoom:16,duration:latest.current.reduced?0:450});},[place.lon,place.lat]);
 useEffect(()=>{if(markerRef.current)markerRef.current.getElement().setAttribute('aria-label',en?'Selected point. Drag to move; or use map centre.':'Выбранная точка. Перетащите или используйте центр карты.');mapRef.current?.getCanvas().setAttribute('aria-label',en?'City map. Arrow keys to pan, plus and minus to zoom.':'Карта города. Стрелки для перемещения, плюс и минус для масштаба.');},[en,ready]);
 useEffect(()=>{const layer=layerRef.current;if(layer)setShade(network?'insufficient':layer.setSun(position.azimuth,position.altitude));else setShade(position.altitude<=0?'night':'insufficient');},[position.azimuth,position.altitude,network]);
 async function build(){const map=mapRef.current;if(!map||!ready||failed||building)return;clear();const token=generation.current,p=latest.current.place;if(Math.abs(p.lat)>85||sourceError.current){setNetwork(true);return;}const style=map.getStyle(),sourceLayer=style.layers.find(l=>'source-layer'in l&&l['source-layer']==='building'&&'source'in l&&style.sources[String(l.source)]?.type==='vector');if(!sourceLayer||!('source'in sourceLayer)){setNetwork(true);return;}const source=String(sourceLayer.source);setBuilding(true);setNetwork(false);setPitched(false);map.fitBounds(areaBounds(p.lon,p.lat),{padding:35,pitch:0,bearing:0,maxZoom:17,duration:0});
  const complete=await new Promise<boolean>(resolve=>{let settled=false;const finish=(ok:boolean)=>{if(settled)return;settled=true;clearTimeout(timer);map.off('idle',check);map.off('sourcedata',check);cancelWait.current=null;resolve(ok);};const check=()=>{if(map.isSourceLoaded(source)&&!map.isMoving())finish(true);},timer=window.setTimeout(()=>finish(false),18000);cancelWait.current=()=>finish(false);map.on('idle',check);map.on('sourcedata',check);queueMicrotask(check);});
  if(token!==generation.current)return;setBuilding(false);if(!complete||sourceError.current){setNetwork(true);return;}
  try{const features=map.querySourceFeatures(source,{sourceLayer:String(sourceLayer['source-layer'])}) as unknown as Feature[];const n=buildNeighborhood(features,p.lon,p.lat);setModel(n);if(!n.parts){setShade('insufficient');return;}const layer=new ShadowLayer(n,p.lon,p.lat);layer.active=visible.current;layerRef.current=layer;map.addLayer(layer);map.moveLayer('helio-boundary-line');setShade(layer.setSun(latest.current.position.azimuth,latest.current.position.altitude));setPitched(true);map.fitBounds(areaBounds(p.lon,p.lat),{padding:innerWidth<600?25:45,pitch:58,bearing:-24,maxZoom:16.8,duration:0});map.easeTo({zoom:Math.min(17,map.getZoom()+.4),duration:latest.current.reduced?0:700});}catch{setNetwork(true);setShade('insufficient');}
 }
 function center(){const p=mapRef.current?.getCenter();if(p)onPoint(wrapLongitude(p.lng),p.lat);}
 const unavailable=failed||network;
 return <section id="map-stage" className={'map-panel'+(failed?' map-unavailable':'')} aria-label={en?'Neighborhood and building shadows':'Квартал и тени зданий'} data-model-parts={model?.parts??0} data-model-vertices={model?.vertices??0} data-model-skipped={model?.skipped??0} data-model-reasons={JSON.stringify(model?.reasons??{})} data-model-incomplete={model?.incomplete??false} data-shade={shade}>
 <div className="map-toolbar"><p><span className="map-step">01 — {en?'Choose a spot':'Выберите точку'}</span>{en?'Click a street or courtyard. Drag the sun pin.':'Нажмите на улицу или двор. Маркер можно перетащить.'}</p><div className="map-buttons"><button onClick={()=>mapRef.current?.zoomIn({duration:reduced?0:200})} disabled={!ready||failed} aria-label={en?'Zoom in':'Приблизить'}>+</button><button onClick={()=>mapRef.current?.zoomOut({duration:reduced?0:200})} disabled={!ready||failed} aria-label={en?'Zoom out':'Отдалить'}>−</button><button onClick={center} disabled={!ready||failed}>{en?'Use map centre':'Выбрать центр карты'}</button></div></div>
 <div ref={host} className="neighborhood-map"/>
 <div className="map-time"><label htmlFor="map-time"><span>{en?'02 — Move the sunlight':'02 — Передвиньте свет'}</span><strong>{timeLabel}</strong><small>☀ {position.altitude.toFixed(1)}° · ↗ {position.azimuth.toFixed(0)}°</small></label><input id="map-time" type="range" min="0" max={Math.ceil(minutes)-1} step="1" value={Math.min(Math.ceil(minutes)-1,minute)} onChange={e=>onMinute(Number(e.target.value))} aria-valuetext={timeLabel}/></div>
 {failed&&<p className="map-fallback" role="status">{en?'This browser cannot display the WebGL map. City search, the solar timeline and the open horizon still work.':'Браузер не может показать карту WebGL. Поиск города, шкала времени и открытый горизонт продолжают работать.'}</p>}
 {network&&<div className="neighborhood-controls"><button onClick={onRetry}>{en?'Retry map':'Загрузить карту заново'}</button></div>}
 {Math.abs(place.lat)>85&&<p className="model-warning">{en?'This point is beyond the map projection limit (85° latitude). Solar calculations still use your exact coordinates; the map cannot model this point.':'Точка за пределами проекции карты (85° широты). Солнечные расчёты используют точные координаты; карта не может построить этот участок.'}</p>}
 <div className="neighborhood-controls"><button className="build-neighborhood" onClick={build} disabled={!ready||failed||building}>{building?(en?'Loading visible block…':'Загружаем видимый участок…'):(en?'Build this neighborhood':'Построить квартал здесь')} <span>300 × 300 {en?'m':'м'} ↗</span></button><button onClick={()=>{const p=!pitched;setPitched(p);mapRef.current?.easeTo({pitch:p?58:0,bearing:p?-24:0,duration:reduced?0:400});}} disabled={!ready||failed} aria-pressed={pitched}>{en?'3D view':'Объёмный вид'}</button><button onClick={()=>mapRef.current?.easeTo({bearing:0,duration:reduced?0:250})} disabled={!ready||failed}>{en?'North ↑':'Север ↑'}</button></div>
 <div className="shade-result" role="status"><span className="status-dot"/><strong>{unavailable?(en?'Map or building data unavailable':'Карта или данные зданий недоступны'):shadeText[shade][en?1:0]}</strong><span>{model?model.parts+(en?' contour parts':' частей контуров'):(en?'Build a block to test the selected point.':'Постройте квартал, чтобы проверить выбранную точку.')}</span></div>
 <p className="model-disclaimer">{en?'Dashed border: the 300 m model boundary. Every height is a cartographic estimate. Point test at 1.6 m above flat ground; loaded buildings only, without trees, weather or obstacles outside the boundary. A clear ray is not a guarantee of sunlight.':'Пунктир — граница модели в 300 м. Все высоты — картографические оценки. Точка проверяется на высоте 1,6 м над плоской землёй; учтены только загруженные здания, без деревьев, погоды и препятствий за границей участка. Свободный луч не гарантирует солнечный свет.'}</p>
 {model?.conditional? <p className="model-warning">{en?`${model.conditional} parts use a conditional height or base (9 m / 0 m when unknown).`:`Для ${model.conditional} частей высота или основание условные (9 м / 0 м при отсутствии данных).`}</p>:null}
 {model?.incomplete&&<p className="model-warning">{en?'Model incomplete: invalid geometry or processing budget reached. The point result is unavailable.':'Модель неполна: некорректная геометрия или достигнут лимит обработки. Результат для точки недоступен.'}</p>}
 {position.altitude>0&&position.altitude<15&&<p className="model-warning">{en?'Low sun: shadows may extend beyond this block. A 100 m building at 10° casts a shadow about 567 m long.':'Низкое солнце: тени могут выходить далеко за этот участок. Здание 100 м при 10° даёт тень около 567 м.'}</p>}
 <p className="map-privacy">{en?'Map requests send the viewed area to OpenFreeMap / its CDN. Solar calculations stay in your browser.':'Запросы карты передают область просмотра OpenFreeMap / его CDN. Солнечные расчёты выполняются в браузере.'} <a href="https://openfreemap.org/privacy/" target="_blank" rel="noopener noreferrer">{en?'Privacy':'Конфиденциальность'}</a> · <a href="https://openfreemap.org/tos/" target="_blank" rel="noopener noreferrer">{en?'Terms':'Условия'}</a></p>
 </section>;
}
