import * as THREE from 'three';
import {MercatorCoordinate,type CustomLayerInterface,type Map} from 'maplibre-gl';
import {solarDirection} from './solar.ts';
import {HALF_SIZE,EYE_HEIGHT,insideBuilding,type Neighborhood,type Building,type Polygon} from './buildings.ts';
export type Shade='night'|'inside'|'shade'|'clear'|'insufficient';
export function mercatorModelMatrix(origin:MercatorCoordinate){const s=origin.meterInMercatorCoordinateUnits();return new THREE.Matrix4().makeTranslation(origin.x,origin.y,origin.z).scale(new THREE.Vector3(s,-s,s)).multiply(new THREE.Matrix4().makeRotationX(Math.PI/2));}
export function polygonMesh(poly:Polygon,b:Building,material:THREE.Material|THREE.Material[]){const shape=new THREE.Shape(poly[0].map(p=>new THREE.Vector2(...p)));for(const h of poly.slice(1))shape.holes.push(new THREE.Path(h.map(p=>new THREE.Vector2(...p))));const geo=new THREE.ExtrudeGeometry(shape,{depth:b.height-b.base,bevelEnabled:false,steps:1,curveSegments:1});geo.rotateX(-Math.PI/2);geo.translate(0,b.base,0);const mesh=new THREE.Mesh(geo,material);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
export function shadeAt(model:Neighborhood,meshes:THREE.Mesh[],azimuth:number,altitude:number):Shade{if(!Number.isFinite(azimuth)||!Number.isFinite(altitude)||Math.abs(altitude)>90)return'insufficient';if(altitude<=0)return'night';if(!model.parts||model.incomplete||meshes.length!==model.parts)return'insufficient';if(model.buildings.some(b=>insideBuilding([0,0],b)))return'inside';const ray=new THREE.Raycaster(new THREE.Vector3(0,EYE_HEIGHT,0),new THREE.Vector3(...solarDirection(azimuth,altitude)),0,2000);return ray.intersectObjects(meshes,false).length?'shade':'clear';}
export class ShadowLayer implements CustomLayerInterface{
 id='helio-neighborhood';type='custom' as const;renderingMode='3d' as const;
 scene=new THREE.Scene();camera=new THREE.Camera();light=new THREE.DirectionalLight(0xffd39b,3);meshes:THREE.Mesh[]=[];renderer?:THREE.WebGLRenderer;map?:Map;origin:MercatorCoordinate;model:Neighborhood;azimuth=180;altitude=45;active=true;bounds=new THREE.Box3();
 constructor(model:Neighborhood,lon:number,lat:number){this.model=model;this.origin=MercatorCoordinate.fromLngLat([lon,lat],0);const material=[new THREE.MeshStandardMaterial({color:0xf3e4c8,roughness:1,side:THREE.DoubleSide}),new THREE.MeshStandardMaterial({color:0xc8bca3,roughness:1,side:THREE.DoubleSide})];for(const b of model.buildings)for(const poly of b.polygons)this.meshes.push(polygonMesh(poly,b,material));this.scene.add(...this.meshes);this.scene.add(new THREE.AmbientLight(0xffffff,1.25));this.light.castShadow=true;Object.assign(this.light.shadow.camera,{near:1,far:1500,left:-250,right:250,top:250,bottom:-250});const size=typeof innerWidth==='number'&&innerWidth<600?1024:2048;this.light.shadow.mapSize.set(size,size);this.light.shadow.bias=-.0002;this.light.shadow.normalBias=.15;this.scene.add(this.light,this.light.target);const ground=new THREE.Mesh(new THREE.PlaneGeometry(HALF_SIZE*2,HALF_SIZE*2),new THREE.ShadowMaterial({opacity:.45}));ground.rotation.x=-Math.PI/2;ground.position.y=.06;ground.receiveShadow=true;this.scene.add(ground);this.scene.updateMatrixWorld(true);this.bounds.setFromObject(ground);for(const mesh of this.meshes)this.bounds.union(new THREE.Box3().setFromObject(mesh));}
 onAdd(map:Map,gl:WebGLRenderingContext|WebGL2RenderingContext){this.map=map;this.renderer=new THREE.WebGLRenderer({canvas:map.getCanvas(),context:gl as WebGL2RenderingContext,antialias:true});this.renderer.autoClear=false;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.setSun(this.azimuth,this.altitude);}
 setSun(azimuth:number,altitude:number){this.azimuth=azimuth;this.altitude=altitude;const valid=Number.isFinite(azimuth)&&Number.isFinite(altitude)&&Math.abs(altitude)<=90;this.light.intensity=valid&&altitude>0?3:0;this.light.castShadow=valid&&altitude>0;if(valid)this.light.position.set(...solarDirection(azimuth,Math.max(.1,altitude))).multiplyScalar(700);this.scene.updateMatrixWorld(true);if(this.light.castShadow)this.fitShadowCamera();if(this.active)this.map?.triggerRepaint();return shadeAt(this.model,this.meshes,azimuth,altitude);}
 private fitShadowCamera(){
  // Include every caster and the receiver, including tall roofs at low solar altitude.
  this.light.shadow.updateMatrices(this.light);const camera=this.light.shadow.camera;let left=Infinity,right=-Infinity,bottom=Infinity,top=-Infinity,near=Infinity,far=-Infinity;
  for(const x of [this.bounds.min.x,this.bounds.max.x])for(const y of [this.bounds.min.y,this.bounds.max.y])for(const z of [this.bounds.min.z,this.bounds.max.z]){const p=new THREE.Vector3(x,y,z).applyMatrix4(camera.matrixWorldInverse);left=Math.min(left,p.x);right=Math.max(right,p.x);bottom=Math.min(bottom,p.y);top=Math.max(top,p.y);near=Math.min(near,-p.z);far=Math.max(far,-p.z);}
  Object.assign(camera,{left:left-3,right:right+3,bottom:bottom-3,top:top+3,near:Math.max(.1,near-3),far:far+3});camera.updateProjectionMatrix();this.light.shadow.updateMatrices(this.light);
 }
 render:CustomLayerInterface['render']=(gl,args)=>{if(!this.active||!this.renderer)return;const m=new THREE.Matrix4().fromArray(args.defaultProjectionData.mainMatrix);this.camera.projectionMatrix.copy(m.multiply(mercatorModelMatrix(this.origin)));this.renderer.resetState();this.renderer.render(this.scene,this.camera);this.renderer.resetState();};
 onRemove(){const materials=new Set<THREE.Material>();this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);}});materials.forEach(m=>m.dispose());this.light.shadow.dispose();this.renderer?.dispose();this.renderer=undefined;this.map=undefined;}
}
